/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ToolsSlugRouteImport } from './routes/tools.$slug'
import { Route as PayTokenRouteImport } from './routes/pay.$token'
import { Route as BlogSearchRouteImport } from './routes/blog.search'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminTransactionsRouteImport } from './routes/admin.transactions'
import { Route as AdminToolsRouteImport } from './routes/admin.tools'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminPricingRouteImport } from './routes/admin.pricing'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminMarketingRouteImport } from './routes/admin.marketing'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminCredentialsRouteImport } from './routes/admin.credentials'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminAwaitingAssignmentsRouteImport } from './routes/admin.awaiting-assignments'
import { Route as AdminAppearanceRouteImport } from './routes/admin.appearance'
import { Route as AdminAdminsRouteImport } from './routes/admin.admins'
import { Route as AdminAccessHealthRouteImport } from './routes/admin.access-health'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated.transactions'
import { Route as AuthenticatedSubscriptionRouteImport } from './routes/_authenticated.subscription'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated.orders'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedChangePasswordRouteImport } from './routes/_authenticated.change-password'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated.billing'
import { Route as DotwellKnownAppleDeveloperMerchantidDomainAssociationRouteImport } from './routes/[.]well-known.apple-developer-merchantid-domain-association'
import { Route as AdminToolsIndexRouteImport } from './routes/admin.tools.index'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin.settings.index'
import { Route as AdminMarketingIndexRouteImport } from './routes/admin.marketing.index'
import { Route as AdminCustomersIndexRouteImport } from './routes/admin.customers.index'
import { Route as AdminBlogIndexRouteImport } from './routes/admin.blog.index'
import { Route as BlogTagSlugRouteImport } from './routes/blog.tag.$slug'
import { Route as BlogCategorySlugRouteImport } from './routes/blog.category.$slug'
import { Route as BlogAuthorIdRouteImport } from './routes/blog.author.$id'
import { Route as ApiSsoSneakwriteConsumeRouteImport } from './routes/api.sso.sneakwrite-consume'
import { Route as ApiPublicBrandLogoRouteImport } from './routes/api.public.brand-logo'
import { Route as ApiDiagWriterAuthResetE2e820b5d66d7e8ca6d74a3fbc5fb108060RouteImport } from './routes/api.diag.writer-auth-reset-e2e-820b5d66d7e8ca6d74a3fbc5fb108060'
import { Route as ApiDiagPhraslyOtpTest4d4dc2a5e7f64203a34e33f071a94554RouteImport } from './routes/api.diag.phrasly-otp-test-4d4dc2a5e7f64203a34e33f071a94554'
import { Route as ApiDiagPhraslyOtpE2e5d90d80acb9f4e5d9fd0d0a4e02b9e71RouteImport } from './routes/api.diag.phrasly-otp-e2e-5d90d80acb9f4e5d9fd0d0a4e02b9e71'
import { Route as ApiDiagPhraslyConcurrencyE2eC7a1f3a87d9e4e54b8bd2a7317e63521RouteImport } from './routes/api.diag.phrasly-concurrency-e2e-c7a1f3a87d9e4e54b8bd2a7317e63521'
import { Route as ApiDiagOneClickE2e8c54e3bf2a704b8cb468db34d36a1c7aRouteImport } from './routes/api.diag.one-click-e2e-8c54e3bf2a704b8cb468db34d36a1c7a'
import { Route as AdminToolsNewRouteImport } from './routes/admin.tools.new'
import { Route as AdminToolsSlugRouteImport } from './routes/admin.tools.$slug'
import { Route as AdminSettingsSystemHealthRouteImport } from './routes/admin.settings.system-health'
import { Route as AdminSettingsStaffRouteImport } from './routes/admin.settings.staff'
import { Route as AdminSettingsPromotionsRouteImport } from './routes/admin.settings.promotions'
import { Route as AdminSettingsProductionReadinessRouteImport } from './routes/admin.settings.production-readiness'
import { Route as AdminSettingsPaymentRecoveryRouteImport } from './routes/admin.settings.payment-recovery'
import { Route as AdminSettingsMigrationReadinessRouteImport } from './routes/admin.settings.migration-readiness'
import { Route as AdminSettingsMigrationGuideRouteImport } from './routes/admin.settings.migration-guide'
import { Route as AdminSettingsMigrationRouteImport } from './routes/admin.settings.migration'
import { Route as AdminSettingsEmergencyRouteImport } from './routes/admin.settings.emergency'
import { Route as AdminSettingsEmailRouteImport } from './routes/admin.settings.email'
import { Route as AdminSettingsCustomPaymentsRouteImport } from './routes/admin.settings.custom-payments'
import { Route as AdminSettingsCurrencyRouteImport } from './routes/admin.settings.currency'
import { Route as AdminSettingsCouponsRouteImport } from './routes/admin.settings.coupons'
import { Route as AdminSettingsCommunicationsRouteImport } from './routes/admin.settings.communications'
import { Route as AdminSettingsBrowserAuthRouteImport } from './routes/admin.settings.browser-auth'
import { Route as AdminSettingsBackupRouteImport } from './routes/admin.settings.backup'
import { Route as AdminSettingsApiKeysRouteImport } from './routes/admin.settings.api-keys'
import { Route as AdminSettingsAnalyticsRouteImport } from './routes/admin.settings.analytics'
import { Route as AdminSettingsActivityRouteImport } from './routes/admin.settings.activity'
import { Route as AdminMarketingMetaRouteImport } from './routes/admin.marketing.meta'
import { Route as AdminMarketingGtmRouteImport } from './routes/admin.marketing.gtm'
import { Route as AdminMarketingEventsRouteImport } from './routes/admin.marketing.events'
import { Route as AdminMarketingAnalyticsRouteImport } from './routes/admin.marketing.analytics'
import { Route as AdminCustomersNewRouteImport } from './routes/admin.customers.new'
import { Route as AdminCustomersInactiveRouteImport } from './routes/admin.customers.inactive'
import { Route as AdminCustomersAllTimeRouteImport } from './routes/admin.customers.all-time'
import { Route as AdminCustomersActiveRouteImport } from './routes/admin.customers.active'
import { Route as AdminCustomersUserIdRouteImport } from './routes/admin.customers.$userId'
import { Route as AdminBlogTagsRouteImport } from './routes/admin.blog.tags'
import { Route as AdminBlogSettingsRouteImport } from './routes/admin.blog.settings'
import { Route as AdminBlogNewRouteImport } from './routes/admin.blog.new'
import { Route as AdminBlogCtasRouteImport } from './routes/admin.blog.ctas'
import { Route as AdminBlogCommentsRouteImport } from './routes/admin.blog.comments'
import { Route as AdminBlogCategoriesRouteImport } from './routes/admin.blog.categories'
import { Route as AdminBlogAiGeneratorRouteImport } from './routes/admin.blog.ai-generator'
import { Route as AuthenticatedReceiptReferenceRouteImport } from './routes/_authenticated.receipt.$reference'
import { Route as AuthenticatedOrderSlugRouteImport } from './routes/_authenticated.order.$slug'
import { Route as ApiPublicWebhooksPaystackRouteImport } from './routes/api.public.webhooks.paystack'
import { Route as ApiPublicWebhooksMonnifyRouteImport } from './routes/api.public.webhooks.monnify'
import { Route as ApiPublicWebhooksFlutterwaveRouteImport } from './routes/api.public.webhooks.flutterwave'
import { Route as ApiPublicHooksEmailDispatcherRouteImport } from './routes/api.public.hooks.email-dispatcher'
import { Route as ApiPublicHooksAutoFulfilPrivateRouteImport } from './routes/api.public.hooks.auto-fulfil-private'
import { Route as AdminBlogIdEditRouteImport } from './routes/admin.blog.$id.edit'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ToolsRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSlugRoute = ToolsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ToolsRoute,
} as any)
const PayTokenRoute = PayTokenRouteImport.update({
  id: '/pay/$token',
  path: '/pay/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSearchRoute = BlogSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/admin/transactions',
  path: '/admin/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminToolsRoute = AdminToolsRouteImport.update({
  id: '/admin/tools',
  path: '/admin/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/admin/reviews',
  path: '/admin/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/admin/pricing',
  path: '/admin/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMarketingRoute = AdminMarketingRouteImport.update({
  id: '/admin/marketing',
  path: '/admin/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/admin/customers',
  path: '/admin/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCredentialsRoute = AdminCredentialsRouteImport.update({
  id: '/admin/credentials',
  path: '/admin/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/admin/blog',
  path: '/admin/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAwaitingAssignmentsRoute =
  AdminAwaitingAssignmentsRouteImport.update({
    id: '/admin/awaiting-assignments',
    path: '/admin/awaiting-assignments',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminAppearanceRoute = AdminAppearanceRouteImport.update({
  id: '/admin/appearance',
  path: '/admin/appearance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminsRoute = AdminAdminsRouteImport.update({
  id: '/admin/admins',
  path: '/admin/admins',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccessHealthRoute = AdminAccessHealthRouteImport.update({
  id: '/admin/access-health',
  path: '/admin/access-health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSubscriptionRoute =
  AuthenticatedSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChangePasswordRoute =
  AuthenticatedChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const DotwellKnownAppleDeveloperMerchantidDomainAssociationRoute =
  DotwellKnownAppleDeveloperMerchantidDomainAssociationRouteImport.update({
    id: '/.well-known/apple-developer-merchantid-domain-association',
    path: '/.well-known/apple-developer-merchantid-domain-association',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminToolsIndexRoute = AdminToolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminToolsRoute,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminMarketingIndexRoute = AdminMarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminMarketingRoute,
} as any)
const AdminCustomersIndexRoute = AdminCustomersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCustomersRoute,
} as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminBlogRoute,
} as any)
const BlogTagSlugRoute = BlogTagSlugRouteImport.update({
  id: '/tag/$slug',
  path: '/tag/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const BlogCategorySlugRoute = BlogCategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const BlogAuthorIdRoute = BlogAuthorIdRouteImport.update({
  id: '/author/$id',
  path: '/author/$id',
  getParentRoute: () => BlogRoute,
} as any)
const ApiSsoSneakwriteConsumeRoute = ApiSsoSneakwriteConsumeRouteImport.update({
  id: '/api/sso/sneakwrite-consume',
  path: '/api/sso/sneakwrite-consume',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBrandLogoRoute = ApiPublicBrandLogoRouteImport.update({
  id: '/api/public/brand-logo',
  path: '/api/public/brand-logo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiagWriterAuthResetE2e820b5d66d7e8ca6d74a3fbc5fb108060Route =
  ApiDiagWriterAuthResetE2e820b5d66d7e8ca6d74a3fbc5fb108060RouteImport.update({
    id: '/api/diag/writer-auth-reset-e2e-820b5d66d7e8ca6d74a3fbc5fb108060',
    path: '/api/diag/writer-auth-reset-e2e-820b5d66d7e8ca6d74a3fbc5fb108060',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDiagPhraslyOtpTest4d4dc2a5e7f64203a34e33f071a94554Route =
  ApiDiagPhraslyOtpTest4d4dc2a5e7f64203a34e33f071a94554RouteImport.update({
    id: '/api/diag/phrasly-otp-test-4d4dc2a5e7f64203a34e33f071a94554',
    path: '/api/diag/phrasly-otp-test-4d4dc2a5e7f64203a34e33f071a94554',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDiagPhraslyOtpE2e5d90d80acb9f4e5d9fd0d0a4e02b9e71Route =
  ApiDiagPhraslyOtpE2e5d90d80acb9f4e5d9fd0d0a4e02b9e71RouteImport.update({
    id: '/api/diag/phrasly-otp-e2e-5d90d80acb9f4e5d9fd0d0a4e02b9e71',
    path: '/api/diag/phrasly-otp-e2e-5d90d80acb9f4e5d9fd0d0a4e02b9e71',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDiagPhraslyConcurrencyE2eC7a1f3a87d9e4e54b8bd2a7317e63521Route =
  ApiDiagPhraslyConcurrencyE2eC7a1f3a87d9e4e54b8bd2a7317e63521RouteImport.update(
    {
      id: '/api/diag/phrasly-concurrency-e2e-c7a1f3a87d9e4e54b8bd2a7317e63521',
      path: '/api/diag/phrasly-concurrency-e2e-c7a1f3a87d9e4e54b8bd2a7317e63521',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const ApiDiagOneClickE2e8c54e3bf2a704b8cb468db34d36a1c7aRoute =
  ApiDiagOneClickE2e8c54e3bf2a704b8cb468db34d36a1c7aRouteImport.update({
    id: '/api/diag/one-click-e2e-8c54e3bf2a704b8cb468db34d36a1c7a',
    path: '/api/diag/one-click-e2e-8c54e3bf2a704b8cb468db34d36a1c7a',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminToolsNewRoute = AdminToolsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminToolsRoute,
} as any)
const AdminToolsSlugRoute = AdminToolsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AdminToolsRoute,
} as any)
const AdminSettingsSystemHealthRoute =
  AdminSettingsSystemHealthRouteImport.update({
    id: '/system-health',
    path: '/system-health',
    getParentRoute: () => AdminSettingsRoute,
  } as any)
const AdminSettingsStaffRoute = AdminSettingsStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsPromotionsRoute = AdminSettingsPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsProductionReadinessRoute =
  AdminSettingsProductionReadinessRouteImport.update({
    id: '/production-readiness',
    path: '/production-readiness',
    getParentRoute: () => AdminSettingsRoute,
  } as any)
const AdminSettingsPaymentRecoveryRoute =
  AdminSettingsPaymentRecoveryRouteImport.update({
    id: '/payment-recovery',
    path: '/payment-recovery',
    getParentRoute: () => AdminSettingsRoute,
  } as any)
const AdminSettingsMigrationReadinessRoute =
  AdminSettingsMigrationReadinessRouteImport.update({
    id: '/migration-readiness',
    path: '/migration-readiness',
    getParentRoute: () => AdminSettingsRoute,
  } as any)
const AdminSettingsMigrationGuideRoute =
  AdminSettingsMigrationGuideRouteImport.update({
    id: '/migration-guide',
    path: '/migration-guide',
    getParentRoute: () => AdminSettingsRoute,
  } as any)
const AdminSettingsMigrationRoute = AdminSettingsMigrationRouteImport.update({
  id: '/migration',
  path: '/migration',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsEmergencyRoute = AdminSettingsEmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsEmailRoute = AdminSettingsEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsCustomPaymentsRoute =
  AdminSettingsCustomPaymentsRouteImport.update({
    id: '/custom-payments',
    path: '/custom-payments',
    getParentRoute: () => AdminSettingsRoute,
  } as any)
const AdminSettingsCurrencyRoute = AdminSettingsCurrencyRouteImport.update({
  id: '/currency',
  path: '/currency',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsCouponsRoute = AdminSettingsCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsCommunicationsRoute =
  AdminSettingsCommunicationsRouteImport.update({
    id: '/communications',
    path: '/communications',
    getParentRoute: () => AdminSettingsRoute,
  } as any)
const AdminSettingsBrowserAuthRoute =
  AdminSettingsBrowserAuthRouteImport.update({
    id: '/browser-auth',
    path: '/browser-auth',
    getParentRoute: () => AdminSettingsRoute,
  } as any)
const AdminSettingsBackupRoute = AdminSettingsBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsApiKeysRoute = AdminSettingsApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsAnalyticsRoute = AdminSettingsAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsActivityRoute = AdminSettingsActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminMarketingMetaRoute = AdminMarketingMetaRouteImport.update({
  id: '/meta',
  path: '/meta',
  getParentRoute: () => AdminMarketingRoute,
} as any)
const AdminMarketingGtmRoute = AdminMarketingGtmRouteImport.update({
  id: '/gtm',
  path: '/gtm',
  getParentRoute: () => AdminMarketingRoute,
} as any)
const AdminMarketingEventsRoute = AdminMarketingEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminMarketingRoute,
} as any)
const AdminMarketingAnalyticsRoute = AdminMarketingAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminMarketingRoute,
} as any)
const AdminCustomersNewRoute = AdminCustomersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminCustomersRoute,
} as any)
const AdminCustomersInactiveRoute = AdminCustomersInactiveRouteImport.update({
  id: '/inactive',
  path: '/inactive',
  getParentRoute: () => AdminCustomersRoute,
} as any)
const AdminCustomersAllTimeRoute = AdminCustomersAllTimeRouteImport.update({
  id: '/all-time',
  path: '/all-time',
  getParentRoute: () => AdminCustomersRoute,
} as any)
const AdminCustomersActiveRoute = AdminCustomersActiveRouteImport.update({
  id: '/active',
  path: '/active',
  getParentRoute: () => AdminCustomersRoute,
} as any)
const AdminCustomersUserIdRoute = AdminCustomersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminCustomersRoute,
} as any)
const AdminBlogTagsRoute = AdminBlogTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AdminBlogRoute,
} as any)
const AdminBlogSettingsRoute = AdminBlogSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminBlogRoute,
} as any)
const AdminBlogNewRoute = AdminBlogNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminBlogRoute,
} as any)
const AdminBlogCtasRoute = AdminBlogCtasRouteImport.update({
  id: '/ctas',
  path: '/ctas',
  getParentRoute: () => AdminBlogRoute,
} as any)
const AdminBlogCommentsRoute = AdminBlogCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => AdminBlogRoute,
} as any)
const AdminBlogCategoriesRoute = AdminBlogCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminBlogRoute,
} as any)
const AdminBlogAiGeneratorRoute = AdminBlogAiGeneratorRouteImport.update({
  id: '/ai-generator',
  path: '/ai-generator',
  getParentRoute: () => AdminBlogRoute,
} as any)
const AuthenticatedReceiptReferenceRoute =
  AuthenticatedReceiptReferenceRouteImport.update({
    id: '/receipt/$reference',
    path: '/receipt/$reference',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrderSlugRoute = AuthenticatedOrderSlugRouteImport.update({
  id: '/order/$slug',
  path: '/order/$slug',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicWebhooksPaystackRoute =
  ApiPublicWebhooksPaystackRouteImport.update({
    id: '/api/public/webhooks/paystack',
    path: '/api/public/webhooks/paystack',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksMonnifyRoute =
  ApiPublicWebhooksMonnifyRouteImport.update({
    id: '/api/public/webhooks/monnify',
    path: '/api/public/webhooks/monnify',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksFlutterwaveRoute =
  ApiPublicWebhooksFlutterwaveRouteImport.update({
    id: '/api/public/webhooks/flutterwave',
    path: '/api/public/webhooks/flutterwave',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksEmailDispatcherRoute =
  ApiPublicHooksEmailDispatcherRouteImport.update({
    id: '/api/public/hooks/email-dispatcher',
    path: '/api/public/hooks/email-dispatcher',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAutoFulfilPrivateRoute =
  ApiPublicHooksAutoFulfilPrivateRouteImport.update({
    id: '/api/public/hooks/auto-fulfil-private',
    path: '/api/public/hooks/auto-fulfil-private',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminBlogIdEditRoute = AdminBlogIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminBlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/.well-known/apple-developer-merchantid-domain-association': typeof DotwellKnownAppleDeveloperMerchantidDomainAssociationRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/admin/access-health': typeof AdminAccessHealthRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/appearance': typeof AdminAppearanceRoute
  '/admin/awaiting-assignments': typeof AdminAwaitingAssignmentsRoute
  '/admin/blog': typeof AdminBlogRouteWithChildren
  '/admin/credentials': typeof AdminCredentialsRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/marketing': typeof AdminMarketingRouteWithChildren
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRouteWithChildren
  '/admin/tools': typeof AdminToolsRouteWithChildren
  '/admin/transactions': typeof AdminTransactionsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/search': typeof BlogSearchRoute
  '/pay/$token': typeof PayTokenRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/order/$slug': typeof AuthenticatedOrderSlugRoute
  '/receipt/$reference': typeof AuthenticatedReceiptReferenceRoute
  '/admin/blog/ai-generator': typeof AdminBlogAiGeneratorRoute
  '/admin/blog/categories': typeof AdminBlogCategoriesRoute
  '/admin/blog/comments': typeof AdminBlogCommentsRoute
  '/admin/blog/ctas': typeof AdminBlogCtasRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/blog/settings': typeof AdminBlogSettingsRoute
  '/admin/blog/tags': typeof AdminBlogTagsRoute
  '/admin/customers/$userId': typeof AdminCustomersUserIdRoute
  '/admin/customers/active': typeof AdminCustomersActiveRoute
  '/admin/customers/all-time': typeof AdminCustomersAllTimeRoute
  '/admin/customers/inactive': typeof AdminCustomersInactiveRoute
  '/admin/customers/new': typeof AdminCustomersNewRoute
  '/admin/marketing/analytics': typeof AdminMarketingAnalyticsRoute
  '/admin/marketing/events': typeof AdminMarketingEventsRoute
  '/admin/marketing/gtm': typeof AdminMarketingGtmRoute
  '/admin/marketing/meta': typeof AdminMarketingMetaRoute
  '/admin/settings/activity': typeof AdminSettingsActivityRoute
  '/admin/settings/analytics': typeof AdminSettingsAnalyticsRoute
  '/admin/settings/api-keys': typeof AdminSettingsApiKeysRoute
  '/admin/settings/backup': typeof AdminSettingsBackupRoute
  '/admin/settings/browser-auth': typeof AdminSettingsBrowserAuthRoute
  '/admin/settings/communications': typeof AdminSettingsCommunicationsRoute
  '/admin/settings/coupons': typeof AdminSettingsCouponsRoute
  '/admin/settings/currency': typeof AdminSettingsCurrencyRoute
  '/admin/settings/custom-payments': typeof AdminSettingsCustomPaymentsRoute
  '/admin/settings/email': typeof AdminSettingsEmailRoute
  '/admin/settings/emergency': typeof AdminSettingsEmergencyRoute
  '/admin/settings/migration': typeof AdminSettingsMigrationRoute
  '/admin/settings/migration-guide': typeof AdminSettingsMigrationGuideRoute
  '/admin/settings/migration-readiness': typeof AdminSettingsMigrationReadinessRoute
  '/admin/settings/payment-recovery': typeof AdminSettingsPaymentRecoveryRoute
  '/admin/settings/production-readiness': typeof AdminSettingsProductionReadinessRoute
  '/admin/settings/promotions': typeof AdminSettingsPromotionsRoute
  '/admin/settings/staff': typeof AdminSettingsStaffRoute
  '/admin/settings/system-health': typeof AdminSettingsSystemHealthRoute
  '/admin/tools/$slug': typeof AdminToolsSlugRoute
  '/admin/tools/new': typeof AdminToolsNewRoute
  '/api/diag/one-click-e2e-8c54e3bf2a704b8cb468db34d36a1c7a': typeof ApiDiagOneClickE2e8c54e3bf2a704b8cb468db34d36a1c7aRoute
  '/api/diag/phrasly-concurrency-e2e-c7a1f3a87d9e4e54b8bd2a7317e63521': typeof ApiDiagPhraslyConcurrencyE2eC7a1f3a87d9e4e54b8bd2a7317e63521Route
  '/api/diag/phrasly-otp-e2e-5d90d80acb9f4e5d9fd0d0a4e02b9e71': typeof ApiDiagPhraslyOtpE2e5d90d80acb9f4e5d9fd0d0a4e02b9e71Route
  '/api/diag/phrasly-otp-test-4d4dc2a5e7f64203a34e33f071a94554': typeof ApiDiagPhraslyOtpTest4d4dc2a5e7f64203a34e33f071a94554Route
  '/api/diag/writer-auth-reset-e2e-820b5d66d7e8ca6d74a3fbc5fb108060': typeof ApiDiagWriterAuthResetE2e820b5d66d7e8ca6d74a3fbc5fb108060Route
  '/api/public/brand-logo': typeof ApiPublicBrandLogoRoute
  '/api/sso/sneakwrite-consume': typeof ApiSsoSneakwriteConsumeRoute
  '/blog/author/$id': typeof BlogAuthorIdRoute
  '/blog/category/$slug': typeof BlogCategorySlugRoute
  '/blog/tag/$slug': typeof BlogTagSlugRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/marketing/': typeof AdminMarketingIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/tools/': typeof AdminToolsIndexRoute
  '/admin/blog/$id/edit': typeof AdminBlogIdEditRoute
  '/api/public/hooks/auto-fulfil-private': typeof ApiPublicHooksAutoFulfilPrivateRoute
  '/api/public/hooks/email-dispatcher': typeof ApiPublicHooksEmailDispatcherRoute
  '/api/public/webhooks/flutterwave': typeof ApiPublicWebhooksFlutterwaveRoute
  '/api/public/webhooks/monnify': typeof ApiPublicWebhooksMonnifyRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/.well-known/apple-developer-merchantid-domain-association': typeof DotwellKnownAppleDeveloperMerchantidDomainAssociationRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/admin/access-health': typeof AdminAccessHealthRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/appearance': typeof AdminAppearanceRoute
  '/admin/awaiting-assignments': typeof AdminAwaitingAssignmentsRoute
  '/admin/credentials': typeof AdminCredentialsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/search': typeof BlogSearchRoute
  '/pay/$token': typeof PayTokenRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/order/$slug': typeof AuthenticatedOrderSlugRoute
  '/receipt/$reference': typeof AuthenticatedReceiptReferenceRoute
  '/admin/blog/ai-generator': typeof AdminBlogAiGeneratorRoute
  '/admin/blog/categories': typeof AdminBlogCategoriesRoute
  '/admin/blog/comments': typeof AdminBlogCommentsRoute
  '/admin/blog/ctas': typeof AdminBlogCtasRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/blog/settings': typeof AdminBlogSettingsRoute
  '/admin/blog/tags': typeof AdminBlogTagsRoute
  '/admin/customers/$userId': typeof AdminCustomersUserIdRoute
  '/admin/customers/active': typeof AdminCustomersActiveRoute
  '/admin/customers/all-time': typeof AdminCustomersAllTimeRoute
  '/admin/customers/inactive': typeof AdminCustomersInactiveRoute
  '/admin/customers/new': typeof AdminCustomersNewRoute
  '/admin/marketing/analytics': typeof AdminMarketingAnalyticsRoute
  '/admin/marketing/events': typeof AdminMarketingEventsRoute
  '/admin/marketing/gtm': typeof AdminMarketingGtmRoute
  '/admin/marketing/meta': typeof AdminMarketingMetaRoute
  '/admin/settings/activity': typeof AdminSettingsActivityRoute
  '/admin/settings/analytics': typeof AdminSettingsAnalyticsRoute
  '/admin/settings/api-keys': typeof AdminSettingsApiKeysRoute
  '/admin/settings/backup': typeof AdminSettingsBackupRoute
  '/admin/settings/browser-auth': typeof AdminSettingsBrowserAuthRoute
  '/admin/settings/communications': typeof AdminSettingsCommunicationsRoute
  '/admin/settings/coupons': typeof AdminSettingsCouponsRoute
  '/admin/settings/currency': typeof AdminSettingsCurrencyRoute
  '/admin/settings/custom-payments': typeof AdminSettingsCustomPaymentsRoute
  '/admin/settings/email': typeof AdminSettingsEmailRoute
  '/admin/settings/emergency': typeof AdminSettingsEmergencyRoute
  '/admin/settings/migration': typeof AdminSettingsMigrationRoute
  '/admin/settings/migration-guide': typeof AdminSettingsMigrationGuideRoute
  '/admin/settings/migration-readiness': typeof AdminSettingsMigrationReadinessRoute
  '/admin/settings/payment-recovery': typeof AdminSettingsPaymentRecoveryRoute
  '/admin/settings/production-readiness': typeof AdminSettingsProductionReadinessRoute
  '/admin/settings/promotions': typeof AdminSettingsPromotionsRoute
  '/admin/settings/staff': typeof AdminSettingsStaffRoute
  '/admin/settings/system-health': typeof AdminSettingsSystemHealthRoute
  '/admin/tools/$slug': typeof AdminToolsSlugRoute
  '/admin/tools/new': typeof AdminToolsNewRoute
  '/api/diag/one-click-e2e-8c54e3bf2a704b8cb468db34d36a1c7a': typeof ApiDiagOneClickE2e8c54e3bf2a704b8cb468db34d36a1c7aRoute
  '/api/diag/phrasly-concurrency-e2e-c7a1f3a87d9e4e54b8bd2a7317e63521': typeof ApiDiagPhraslyConcurrencyE2eC7a1f3a87d9e4e54b8bd2a7317e63521Route
  '/api/diag/phrasly-otp-e2e-5d90d80acb9f4e5d9fd0d0a4e02b9e71': typeof ApiDiagPhraslyOtpE2e5d90d80acb9f4e5d9fd0d0a4e02b9e71Route
  '/api/diag/phrasly-otp-test-4d4dc2a5e7f64203a34e33f071a94554': typeof ApiDiagPhraslyOtpTest4d4dc2a5e7f64203a34e33f071a94554Route
  '/api/diag/writer-auth-reset-e2e-820b5d66d7e8ca6d74a3fbc5fb108060': typeof ApiDiagWriterAuthResetE2e820b5d66d7e8ca6d74a3fbc5fb108060Route
  '/api/public/brand-logo': typeof ApiPublicBrandLogoRoute
  '/api/sso/sneakwrite-consume': typeof ApiSsoSneakwriteConsumeRoute
  '/blog/author/$id': typeof BlogAuthorIdRoute
  '/blog/category/$slug': typeof BlogCategorySlugRoute
  '/blog/tag/$slug': typeof BlogTagSlugRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/admin/customers': typeof AdminCustomersIndexRoute
  '/admin/marketing': typeof AdminMarketingIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/tools': typeof AdminToolsIndexRoute
  '/admin/blog/$id/edit': typeof AdminBlogIdEditRoute
  '/api/public/hooks/auto-fulfil-private': typeof ApiPublicHooksAutoFulfilPrivateRoute
  '/api/public/hooks/email-dispatcher': typeof ApiPublicHooksEmailDispatcherRoute
  '/api/public/webhooks/flutterwave': typeof ApiPublicWebhooksFlutterwaveRoute
  '/api/public/webhooks/monnify': typeof ApiPublicWebhooksMonnifyRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/.well-known/apple-developer-merchantid-domain-association': typeof DotwellKnownAppleDeveloperMerchantidDomainAssociationRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/change-password': typeof AuthenticatedChangePasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/subscription': typeof AuthenticatedSubscriptionRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/admin/access-health': typeof AdminAccessHealthRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/appearance': typeof AdminAppearanceRoute
  '/admin/awaiting-assignments': typeof AdminAwaitingAssignmentsRoute
  '/admin/blog': typeof AdminBlogRouteWithChildren
  '/admin/credentials': typeof AdminCredentialsRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/marketing': typeof AdminMarketingRouteWithChildren
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRouteWithChildren
  '/admin/tools': typeof AdminToolsRouteWithChildren
  '/admin/transactions': typeof AdminTransactionsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/search': typeof BlogSearchRoute
  '/pay/$token': typeof PayTokenRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/_authenticated/order/$slug': typeof AuthenticatedOrderSlugRoute
  '/_authenticated/receipt/$reference': typeof AuthenticatedReceiptReferenceRoute
  '/admin/blog/ai-generator': typeof AdminBlogAiGeneratorRoute
  '/admin/blog/categories': typeof AdminBlogCategoriesRoute
  '/admin/blog/comments': typeof AdminBlogCommentsRoute
  '/admin/blog/ctas': typeof AdminBlogCtasRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/blog/settings': typeof AdminBlogSettingsRoute
  '/admin/blog/tags': typeof AdminBlogTagsRoute
  '/admin/customers/$userId': typeof AdminCustomersUserIdRoute
  '/admin/customers/active': typeof AdminCustomersActiveRoute
  '/admin/customers/all-time': typeof AdminCustomersAllTimeRoute
  '/admin/customers/inactive': typeof AdminCustomersInactiveRoute
  '/admin/customers/new': typeof AdminCustomersNewRoute
  '/admin/marketing/analytics': typeof AdminMarketingAnalyticsRoute
  '/admin/marketing/events': typeof AdminMarketingEventsRoute
  '/admin/marketing/gtm': typeof AdminMarketingGtmRoute
  '/admin/marketing/meta': typeof AdminMarketingMetaRoute
  '/admin/settings/activity': typeof AdminSettingsActivityRoute
  '/admin/settings/analytics': typeof AdminSettingsAnalyticsRoute
  '/admin/settings/api-keys': typeof AdminSettingsApiKeysRoute
  '/admin/settings/backup': typeof AdminSettingsBackupRoute
  '/admin/settings/browser-auth': typeof AdminSettingsBrowserAuthRoute
  '/admin/settings/communications': typeof AdminSettingsCommunicationsRoute
  '/admin/settings/coupons': typeof AdminSettingsCouponsRoute
  '/admin/settings/currency': typeof AdminSettingsCurrencyRoute
  '/admin/settings/custom-payments': typeof AdminSettingsCustomPaymentsRoute
  '/admin/settings/email': typeof AdminSettingsEmailRoute
  '/admin/settings/emergency': typeof AdminSettingsEmergencyRoute
  '/admin/settings/migration': typeof AdminSettingsMigrationRoute
  '/admin/settings/migration-guide': typeof AdminSettingsMigrationGuideRoute
  '/admin/settings/migration-readiness': typeof AdminSettingsMigrationReadinessRoute
  '/admin/settings/payment-recovery': typeof AdminSettingsPaymentRecoveryRoute
  '/admin/settings/production-readiness': typeof AdminSettingsProductionReadinessRoute
  '/admin/settings/promotions': typeof AdminSettingsPromotionsRoute
  '/admin/settings/staff': typeof AdminSettingsStaffRoute
  '/admin/settings/system-health': typeof AdminSettingsSystemHealthRoute
  '/admin/tools/$slug': typeof AdminToolsSlugRoute
  '/admin/tools/new': typeof AdminToolsNewRoute
  '/api/diag/one-click-e2e-8c54e3bf2a704b8cb468db34d36a1c7a': typeof ApiDiagOneClickE2e8c54e3bf2a704b8cb468db34d36a1c7aRoute
  '/api/diag/phrasly-concurrency-e2e-c7a1f3a87d9e4e54b8bd2a7317e63521': typeof ApiDiagPhraslyConcurrencyE2eC7a1f3a87d9e4e54b8bd2a7317e63521Route
  '/api/diag/phrasly-otp-e2e-5d90d80acb9f4e5d9fd0d0a4e02b9e71': typeof ApiDiagPhraslyOtpE2e5d90d80acb9f4e5d9fd0d0a4e02b9e71Route
  '/api/diag/phrasly-otp-test-4d4dc2a5e7f64203a34e33f071a94554': typeof ApiDiagPhraslyOtpTest4d4dc2a5e7f64203a34e33f071a94554Route
  '/api/diag/writer-auth-reset-e2e-820b5d66d7e8ca6d74a3fbc5fb108060': typeof ApiDiagWriterAuthResetE2e820b5d66d7e8ca6d74a3fbc5fb108060Route
  '/api/public/brand-logo': typeof ApiPublicBrandLogoRoute
  '/api/sso/sneakwrite-consume': typeof ApiSsoSneakwriteConsumeRoute
  '/blog/author/$id': typeof BlogAuthorIdRoute
  '/blog/category/$slug': typeof BlogCategorySlugRoute
  '/blog/tag/$slug': typeof BlogTagSlugRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/marketing/': typeof AdminMarketingIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/tools/': typeof AdminToolsIndexRoute
  '/admin/blog/$id/edit': typeof AdminBlogIdEditRoute
  '/api/public/hooks/auto-fulfil-private': typeof ApiPublicHooksAutoFulfilPrivateRoute
  '/api/public/hooks/email-dispatcher': typeof ApiPublicHooksEmailDispatcherRoute
  '/api/public/webhooks/flutterwave': typeof ApiPublicWebhooksFlutterwaveRoute
  '/api/public/webhooks/monnify': typeof ApiPublicWebhooksMonnifyRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/cookies'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/tools'
    | '/.well-known/apple-developer-merchantid-domain-association'
    | '/billing'
    | '/change-password'
    | '/dashboard'
    | '/orders'
    | '/profile'
    | '/subscription'
    | '/transactions'
    | '/admin/access-health'
    | '/admin/admins'
    | '/admin/appearance'
    | '/admin/awaiting-assignments'
    | '/admin/blog'
    | '/admin/credentials'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/marketing'
    | '/admin/orders'
    | '/admin/pricing'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/tools'
    | '/admin/transactions'
    | '/blog/$slug'
    | '/blog/search'
    | '/pay/$token'
    | '/tools/$slug'
    | '/admin/'
    | '/blog/'
    | '/tools/'
    | '/order/$slug'
    | '/receipt/$reference'
    | '/admin/blog/ai-generator'
    | '/admin/blog/categories'
    | '/admin/blog/comments'
    | '/admin/blog/ctas'
    | '/admin/blog/new'
    | '/admin/blog/settings'
    | '/admin/blog/tags'
    | '/admin/customers/$userId'
    | '/admin/customers/active'
    | '/admin/customers/all-time'
    | '/admin/customers/inactive'
    | '/admin/customers/new'
    | '/admin/marketing/analytics'
    | '/admin/marketing/events'
    | '/admin/marketing/gtm'
    | '/admin/marketing/meta'
    | '/admin/settings/activity'
    | '/admin/settings/analytics'
    | '/admin/settings/api-keys'
    | '/admin/settings/backup'
    | '/admin/settings/browser-auth'
    | '/admin/settings/communications'
    | '/admin/settings/coupons'
    | '/admin/settings/currency'
    | '/admin/settings/custom-payments'
    | '/admin/settings/email'
    | '/admin/settings/emergency'
    | '/admin/settings/migration'
    | '/admin/settings/migration-guide'
    | '/admin/settings/migration-readiness'
    | '/admin/settings/payment-recovery'
    | '/admin/settings/production-readiness'
    | '/admin/settings/promotions'
    | '/admin/settings/staff'
    | '/admin/settings/system-health'
    | '/admin/tools/$slug'
    | '/admin/tools/new'
    | '/api/diag/one-click-e2e-8c54e3bf2a704b8cb468db34d36a1c7a'
    | '/api/diag/phrasly-concurrency-e2e-c7a1f3a87d9e4e54b8bd2a7317e63521'
    | '/api/diag/phrasly-otp-e2e-5d90d80acb9f4e5d9fd0d0a4e02b9e71'
    | '/api/diag/phrasly-otp-test-4d4dc2a5e7f64203a34e33f071a94554'
    | '/api/diag/writer-auth-reset-e2e-820b5d66d7e8ca6d74a3fbc5fb108060'
    | '/api/public/brand-logo'
    | '/api/sso/sneakwrite-consume'
    | '/blog/author/$id'
    | '/blog/category/$slug'
    | '/blog/tag/$slug'
    | '/admin/blog/'
    | '/admin/customers/'
    | '/admin/marketing/'
    | '/admin/settings/'
    | '/admin/tools/'
    | '/admin/blog/$id/edit'
    | '/api/public/hooks/auto-fulfil-private'
    | '/api/public/hooks/email-dispatcher'
    | '/api/public/webhooks/flutterwave'
    | '/api/public/webhooks/monnify'
    | '/api/public/webhooks/paystack'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/cookies'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/.well-known/apple-developer-merchantid-domain-association'
    | '/billing'
    | '/change-password'
    | '/dashboard'
    | '/orders'
    | '/profile'
    | '/subscription'
    | '/transactions'
    | '/admin/access-health'
    | '/admin/admins'
    | '/admin/appearance'
    | '/admin/awaiting-assignments'
    | '/admin/credentials'
    | '/admin/dashboard'
    | '/admin/orders'
    | '/admin/pricing'
    | '/admin/reviews'
    | '/admin/transactions'
    | '/blog/$slug'
    | '/blog/search'
    | '/pay/$token'
    | '/tools/$slug'
    | '/admin'
    | '/blog'
    | '/tools'
    | '/order/$slug'
    | '/receipt/$reference'
    | '/admin/blog/ai-generator'
    | '/admin/blog/categories'
    | '/admin/blog/comments'
    | '/admin/blog/ctas'
    | '/admin/blog/new'
    | '/admin/blog/settings'
    | '/admin/blog/tags'
    | '/admin/customers/$userId'
    | '/admin/customers/active'
    | '/admin/customers/all-time'
    | '/admin/customers/inactive'
    | '/admin/customers/new'
    | '/admin/marketing/analytics'
    | '/admin/marketing/events'
    | '/admin/marketing/gtm'
    | '/admin/marketing/meta'
    | '/admin/settings/activity'
    | '/admin/settings/analytics'
    | '/admin/settings/api-keys'
    | '/admin/settings/backup'
    | '/admin/settings/browser-auth'
    | '/admin/settings/communications'
    | '/admin/settings/coupons'
    | '/admin/settings/currency'
    | '/admin/settings/custom-payments'
    | '/admin/settings/email'
    | '/admin/settings/emergency'
    | '/admin/settings/migration'
    | '/admin/settings/migration-guide'
    | '/admin/settings/migration-readiness'
    | '/admin/settings/payment-recovery'
    | '/admin/settings/production-readiness'
    | '/admin/settings/promotions'
    | '/admin/settings/staff'
    | '/admin/settings/system-health'
    | '/admin/tools/$slug'
    | '/admin/tools/new'
    | '/api/diag/one-click-e2e-8c54e3bf2a704b8cb468db34d36a1c7a'
    | '/api/diag/phrasly-concurrency-e2e-c7a1f3a87d9e4e54b8bd2a7317e63521'
    | '/api/diag/phrasly-otp-e2e-5d90d80acb9f4e5d9fd0d0a4e02b9e71'
    | '/api/diag/phrasly-otp-test-4d4dc2a5e7f64203a34e33f071a94554'
    | '/api/diag/writer-auth-reset-e2e-820b5d66d7e8ca6d74a3fbc5fb108060'
    | '/api/public/brand-logo'
    | '/api/sso/sneakwrite-consume'
    | '/blog/author/$id'
    | '/blog/category/$slug'
    | '/blog/tag/$slug'
    | '/admin/blog'
    | '/admin/customers'
    | '/admin/marketing'
    | '/admin/settings'
    | '/admin/tools'
    | '/admin/blog/$id/edit'
    | '/api/public/hooks/auto-fulfil-private'
    | '/api/public/hooks/email-dispatcher'
    | '/api/public/webhooks/flutterwave'
    | '/api/public/webhooks/monnify'
    | '/api/public/webhooks/paystack'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/blog'
    | '/contact'
    | '/cookies'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/tools'
    | '/.well-known/apple-developer-merchantid-domain-association'
    | '/_authenticated/billing'
    | '/_authenticated/change-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/orders'
    | '/_authenticated/profile'
    | '/_authenticated/subscription'
    | '/_authenticated/transactions'
    | '/admin/access-health'
    | '/admin/admins'
    | '/admin/appearance'
    | '/admin/awaiting-assignments'
    | '/admin/blog'
    | '/admin/credentials'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/marketing'
    | '/admin/orders'
    | '/admin/pricing'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/tools'
    | '/admin/transactions'
    | '/blog/$slug'
    | '/blog/search'
    | '/pay/$token'
    | '/tools/$slug'
    | '/admin/'
    | '/blog/'
    | '/tools/'
    | '/_authenticated/order/$slug'
    | '/_authenticated/receipt/$reference'
    | '/admin/blog/ai-generator'
    | '/admin/blog/categories'
    | '/admin/blog/comments'
    | '/admin/blog/ctas'
    | '/admin/blog/new'
    | '/admin/blog/settings'
    | '/admin/blog/tags'
    | '/admin/customers/$userId'
    | '/admin/customers/active'
    | '/admin/customers/all-time'
    | '/admin/customers/inactive'
    | '/admin/customers/new'
    | '/admin/marketing/analytics'
    | '/admin/marketing/events'
    | '/admin/marketing/gtm'
    | '/admin/marketing/meta'
    | '/admin/settings/activity'
    | '/admin/settings/analytics'
    | '/admin/settings/api-keys'
    | '/admin/settings/backup'
    | '/admin/settings/browser-auth'
    | '/admin/settings/communications'
    | '/admin/settings/coupons'
    | '/admin/settings/currency'
    | '/admin/settings/custom-payments'
    | '/admin/settings/email'
    | '/admin/settings/emergency'
    | '/admin/settings/migration'
    | '/admin/settings/migration-guide'
    | '/admin/settings/migration-readiness'
    | '/admin/settings/payment-recovery'
    | '/admin/settings/production-readiness'
    | '/admin/settings/promotions'
    | '/admin/settings/staff'
    | '/admin/settings/system-health'
    | '/admin/tools/$slug'
    | '/admin/tools/new'
    | '/api/diag/one-click-e2e-8c54e3bf2a704b8cb468db34d36a1c7a'
    | '/api/diag/phrasly-concurrency-e2e-c7a1f3a87d9e4e54b8bd2a7317e63521'
    | '/api/diag/phrasly-otp-e2e-5d90d80acb9f4e5d9fd0d0a4e02b9e71'
    | '/api/diag/phrasly-otp-test-4d4dc2a5e7f64203a34e33f071a94554'
    | '/api/diag/writer-auth-reset-e2e-820b5d66d7e8ca6d74a3fbc5fb108060'
    | '/api/public/brand-logo'
    | '/api/sso/sneakwrite-consume'
    | '/blog/author/$id'
    | '/blog/category/$slug'
    | '/blog/tag/$slug'
    | '/admin/blog/'
    | '/admin/customers/'
    | '/admin/marketing/'
    | '/admin/settings/'
    | '/admin/tools/'
    | '/admin/blog/$id/edit'
    | '/api/public/hooks/auto-fulfil-private'
    | '/api/public/hooks/email-dispatcher'
    | '/api/public/webhooks/flutterwave'
    | '/api/public/webhooks/monnify'
    | '/api/public/webhooks/paystack'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  ToolsRoute: typeof ToolsRouteWithChildren
  DotwellKnownAppleDeveloperMerchantidDomainAssociationRoute: typeof DotwellKnownAppleDeveloperMerchantidDomainAssociationRoute
  AdminAccessHealthRoute: typeof AdminAccessHealthRoute
  AdminAdminsRoute: typeof AdminAdminsRoute
  AdminAppearanceRoute: typeof AdminAppearanceRoute
  AdminAwaitingAssignmentsRoute: typeof AdminAwaitingAssignmentsRoute
  AdminBlogRoute: typeof AdminBlogRouteWithChildren
  AdminCredentialsRoute: typeof AdminCredentialsRoute
  AdminCustomersRoute: typeof AdminCustomersRouteWithChildren
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminMarketingRoute: typeof AdminMarketingRouteWithChildren
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSettingsRoute: typeof AdminSettingsRouteWithChildren
  AdminToolsRoute: typeof AdminToolsRouteWithChildren
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  PayTokenRoute: typeof PayTokenRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiDiagOneClickE2e8c54e3bf2a704b8cb468db34d36a1c7aRoute: typeof ApiDiagOneClickE2e8c54e3bf2a704b8cb468db34d36a1c7aRoute
  ApiDiagPhraslyConcurrencyE2eC7a1f3a87d9e4e54b8bd2a7317e63521Route: typeof ApiDiagPhraslyConcurrencyE2eC7a1f3a87d9e4e54b8bd2a7317e63521Route
  ApiDiagPhraslyOtpE2e5d90d80acb9f4e5d9fd0d0a4e02b9e71Route: typeof ApiDiagPhraslyOtpE2e5d90d80acb9f4e5d9fd0d0a4e02b9e71Route
  ApiDiagPhraslyOtpTest4d4dc2a5e7f64203a34e33f071a94554Route: typeof ApiDiagPhraslyOtpTest4d4dc2a5e7f64203a34e33f071a94554Route
  ApiDiagWriterAuthResetE2e820b5d66d7e8ca6d74a3fbc5fb108060Route: typeof ApiDiagWriterAuthResetE2e820b5d66d7e8ca6d74a3fbc5fb108060Route
  ApiPublicBrandLogoRoute: typeof ApiPublicBrandLogoRoute
  ApiSsoSneakwriteConsumeRoute: typeof ApiSsoSneakwriteConsumeRoute
  ApiPublicHooksAutoFulfilPrivateRoute: typeof ApiPublicHooksAutoFulfilPrivateRoute
  ApiPublicHooksEmailDispatcherRoute: typeof ApiPublicHooksEmailDispatcherRoute
  ApiPublicWebhooksFlutterwaveRoute: typeof ApiPublicWebhooksFlutterwaveRoute
  ApiPublicWebhooksMonnifyRoute: typeof ApiPublicWebhooksMonnifyRoute
  ApiPublicWebhooksPaystackRoute: typeof ApiPublicWebhooksPaystackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$slug': {
      id: '/tools/$slug'
      path: '/$slug'
      fullPath: '/tools/$slug'
      preLoaderRoute: typeof ToolsSlugRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/pay/$token': {
      id: '/pay/$token'
      path: '/pay/$token'
      fullPath: '/pay/$token'
      preLoaderRoute: typeof PayTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/search': {
      id: '/blog/search'
      path: '/search'
      fullPath: '/blog/search'
      preLoaderRoute: typeof BlogSearchRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/admin/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tools': {
      id: '/admin/tools'
      path: '/admin/tools'
      fullPath: '/admin/tools'
      preLoaderRoute: typeof AdminToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/admin/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/admin/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/marketing': {
      id: '/admin/marketing'
      path: '/admin/marketing'
      fullPath: '/admin/marketing'
      preLoaderRoute: typeof AdminMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/credentials': {
      id: '/admin/credentials'
      path: '/admin/credentials'
      fullPath: '/admin/credentials'
      preLoaderRoute: typeof AdminCredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/admin/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/awaiting-assignments': {
      id: '/admin/awaiting-assignments'
      path: '/admin/awaiting-assignments'
      fullPath: '/admin/awaiting-assignments'
      preLoaderRoute: typeof AdminAwaitingAssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/appearance': {
      id: '/admin/appearance'
      path: '/admin/appearance'
      fullPath: '/admin/appearance'
      preLoaderRoute: typeof AdminAppearanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/admins': {
      id: '/admin/admins'
      path: '/admin/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/access-health': {
      id: '/admin/access-health'
      path: '/admin/access-health'
      fullPath: '/admin/access-health'
      preLoaderRoute: typeof AdminAccessHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/subscription': {
      id: '/_authenticated/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof AuthenticatedSubscriptionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/change-password': {
      id: '/_authenticated/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthenticatedChangePasswordRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/.well-known/apple-developer-merchantid-domain-association': {
      id: '/.well-known/apple-developer-merchantid-domain-association'
      path: '/.well-known/apple-developer-merchantid-domain-association'
      fullPath: '/.well-known/apple-developer-merchantid-domain-association'
      preLoaderRoute: typeof DotwellKnownAppleDeveloperMerchantidDomainAssociationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tools/': {
      id: '/admin/tools/'
      path: '/'
      fullPath: '/admin/tools/'
      preLoaderRoute: typeof AdminToolsIndexRouteImport
      parentRoute: typeof AdminToolsRoute
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/marketing/': {
      id: '/admin/marketing/'
      path: '/'
      fullPath: '/admin/marketing/'
      preLoaderRoute: typeof AdminMarketingIndexRouteImport
      parentRoute: typeof AdminMarketingRoute
    }
    '/admin/customers/': {
      id: '/admin/customers/'
      path: '/'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof AdminCustomersIndexRouteImport
      parentRoute: typeof AdminCustomersRoute
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof AdminBlogRoute
    }
    '/blog/tag/$slug': {
      id: '/blog/tag/$slug'
      path: '/tag/$slug'
      fullPath: '/blog/tag/$slug'
      preLoaderRoute: typeof BlogTagSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/category/$slug': {
      id: '/blog/category/$slug'
      path: '/category/$slug'
      fullPath: '/blog/category/$slug'
      preLoaderRoute: typeof BlogCategorySlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/author/$id': {
      id: '/blog/author/$id'
      path: '/author/$id'
      fullPath: '/blog/author/$id'
      preLoaderRoute: typeof BlogAuthorIdRouteImport
      parentRoute: typeof BlogRoute
    }
    '/api/sso/sneakwrite-consume': {
      id: '/api/sso/sneakwrite-consume'
      path: '/api/sso/sneakwrite-consume'
      fullPath: '/api/sso/sneakwrite-consume'
      preLoaderRoute: typeof ApiSsoSneakwriteConsumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/brand-logo': {
      id: '/api/public/brand-logo'
      path: '/api/public/brand-logo'
      fullPath: '/api/public/brand-logo'
      preLoaderRoute: typeof ApiPublicBrandLogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/diag/writer-auth-reset-e2e-820b5d66d7e8ca6d74a3fbc5fb108060': {
      id: '/api/diag/writer-auth-reset-e2e-820b5d66d7e8ca6d74a3fbc5fb108060'
      path: '/api/diag/writer-auth-reset-e2e-820b5d66d7e8ca6d74a3fbc5fb108060'
      fullPath: '/api/diag/writer-auth-reset-e2e-820b5d66d7e8ca6d74a3fbc5fb108060'
      preLoaderRoute: typeof ApiDiagWriterAuthResetE2e820b5d66d7e8ca6d74a3fbc5fb108060RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/diag/phrasly-otp-test-4d4dc2a5e7f64203a34e33f071a94554': {
      id: '/api/diag/phrasly-otp-test-4d4dc2a5e7f64203a34e33f071a94554'
      path: '/api/diag/phrasly-otp-test-4d4dc2a5e7f64203a34e33f071a94554'
      fullPath: '/api/diag/phrasly-otp-test-4d4dc2a5e7f64203a34e33f071a94554'
      preLoaderRoute: typeof ApiDiagPhraslyOtpTest4d4dc2a5e7f64203a34e33f071a94554RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/diag/phrasly-otp-e2e-5d90d80acb9f4e5d9fd0d0a4e02b9e71': {
      id: '/api/diag/phrasly-otp-e2e-5d90d80acb9f4e5d9fd0d0a4e02b9e71'
      path: '/api/diag/phrasly-otp-e2e-5d90d80acb9f4e5d9fd0d0a4e02b9e71'
      fullPath: '/api/diag/phrasly-otp-e2e-5d90d80acb9f4e5d9fd0d0a4e02b9e71'
      preLoaderRoute: typeof ApiDiagPhraslyOtpE2e5d90d80acb9f4e5d9fd0d0a4e02b9e71RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/diag/phrasly-concurrency-e2e-c7a1f3a87d9e4e54b8bd2a7317e63521': {
      id: '/api/diag/phrasly-concurrency-e2e-c7a1f3a87d9e4e54b8bd2a7317e63521'
      path: '/api/diag/phrasly-concurrency-e2e-c7a1f3a87d9e4e54b8bd2a7317e63521'
      fullPath: '/api/diag/phrasly-concurrency-e2e-c7a1f3a87d9e4e54b8bd2a7317e63521'
      preLoaderRoute: typeof ApiDiagPhraslyConcurrencyE2eC7a1f3a87d9e4e54b8bd2a7317e63521RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/diag/one-click-e2e-8c54e3bf2a704b8cb468db34d36a1c7a': {
      id: '/api/diag/one-click-e2e-8c54e3bf2a704b8cb468db34d36a1c7a'
      path: '/api/diag/one-click-e2e-8c54e3bf2a704b8cb468db34d36a1c7a'
      fullPath: '/api/diag/one-click-e2e-8c54e3bf2a704b8cb468db34d36a1c7a'
      preLoaderRoute: typeof ApiDiagOneClickE2e8c54e3bf2a704b8cb468db34d36a1c7aRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tools/new': {
      id: '/admin/tools/new'
      path: '/new'
      fullPath: '/admin/tools/new'
      preLoaderRoute: typeof AdminToolsNewRouteImport
      parentRoute: typeof AdminToolsRoute
    }
    '/admin/tools/$slug': {
      id: '/admin/tools/$slug'
      path: '/$slug'
      fullPath: '/admin/tools/$slug'
      preLoaderRoute: typeof AdminToolsSlugRouteImport
      parentRoute: typeof AdminToolsRoute
    }
    '/admin/settings/system-health': {
      id: '/admin/settings/system-health'
      path: '/system-health'
      fullPath: '/admin/settings/system-health'
      preLoaderRoute: typeof AdminSettingsSystemHealthRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/staff': {
      id: '/admin/settings/staff'
      path: '/staff'
      fullPath: '/admin/settings/staff'
      preLoaderRoute: typeof AdminSettingsStaffRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/promotions': {
      id: '/admin/settings/promotions'
      path: '/promotions'
      fullPath: '/admin/settings/promotions'
      preLoaderRoute: typeof AdminSettingsPromotionsRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/production-readiness': {
      id: '/admin/settings/production-readiness'
      path: '/production-readiness'
      fullPath: '/admin/settings/production-readiness'
      preLoaderRoute: typeof AdminSettingsProductionReadinessRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/payment-recovery': {
      id: '/admin/settings/payment-recovery'
      path: '/payment-recovery'
      fullPath: '/admin/settings/payment-recovery'
      preLoaderRoute: typeof AdminSettingsPaymentRecoveryRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/migration-readiness': {
      id: '/admin/settings/migration-readiness'
      path: '/migration-readiness'
      fullPath: '/admin/settings/migration-readiness'
      preLoaderRoute: typeof AdminSettingsMigrationReadinessRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/migration-guide': {
      id: '/admin/settings/migration-guide'
      path: '/migration-guide'
      fullPath: '/admin/settings/migration-guide'
      preLoaderRoute: typeof AdminSettingsMigrationGuideRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/migration': {
      id: '/admin/settings/migration'
      path: '/migration'
      fullPath: '/admin/settings/migration'
      preLoaderRoute: typeof AdminSettingsMigrationRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/emergency': {
      id: '/admin/settings/emergency'
      path: '/emergency'
      fullPath: '/admin/settings/emergency'
      preLoaderRoute: typeof AdminSettingsEmergencyRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/email': {
      id: '/admin/settings/email'
      path: '/email'
      fullPath: '/admin/settings/email'
      preLoaderRoute: typeof AdminSettingsEmailRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/custom-payments': {
      id: '/admin/settings/custom-payments'
      path: '/custom-payments'
      fullPath: '/admin/settings/custom-payments'
      preLoaderRoute: typeof AdminSettingsCustomPaymentsRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/currency': {
      id: '/admin/settings/currency'
      path: '/currency'
      fullPath: '/admin/settings/currency'
      preLoaderRoute: typeof AdminSettingsCurrencyRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/coupons': {
      id: '/admin/settings/coupons'
      path: '/coupons'
      fullPath: '/admin/settings/coupons'
      preLoaderRoute: typeof AdminSettingsCouponsRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/communications': {
      id: '/admin/settings/communications'
      path: '/communications'
      fullPath: '/admin/settings/communications'
      preLoaderRoute: typeof AdminSettingsCommunicationsRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/browser-auth': {
      id: '/admin/settings/browser-auth'
      path: '/browser-auth'
      fullPath: '/admin/settings/browser-auth'
      preLoaderRoute: typeof AdminSettingsBrowserAuthRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/backup': {
      id: '/admin/settings/backup'
      path: '/backup'
      fullPath: '/admin/settings/backup'
      preLoaderRoute: typeof AdminSettingsBackupRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/api-keys': {
      id: '/admin/settings/api-keys'
      path: '/api-keys'
      fullPath: '/admin/settings/api-keys'
      preLoaderRoute: typeof AdminSettingsApiKeysRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/analytics': {
      id: '/admin/settings/analytics'
      path: '/analytics'
      fullPath: '/admin/settings/analytics'
      preLoaderRoute: typeof AdminSettingsAnalyticsRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/activity': {
      id: '/admin/settings/activity'
      path: '/activity'
      fullPath: '/admin/settings/activity'
      preLoaderRoute: typeof AdminSettingsActivityRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/marketing/meta': {
      id: '/admin/marketing/meta'
      path: '/meta'
      fullPath: '/admin/marketing/meta'
      preLoaderRoute: typeof AdminMarketingMetaRouteImport
      parentRoute: typeof AdminMarketingRoute
    }
    '/admin/marketing/gtm': {
      id: '/admin/marketing/gtm'
      path: '/gtm'
      fullPath: '/admin/marketing/gtm'
      preLoaderRoute: typeof AdminMarketingGtmRouteImport
      parentRoute: typeof AdminMarketingRoute
    }
    '/admin/marketing/events': {
      id: '/admin/marketing/events'
      path: '/events'
      fullPath: '/admin/marketing/events'
      preLoaderRoute: typeof AdminMarketingEventsRouteImport
      parentRoute: typeof AdminMarketingRoute
    }
    '/admin/marketing/analytics': {
      id: '/admin/marketing/analytics'
      path: '/analytics'
      fullPath: '/admin/marketing/analytics'
      preLoaderRoute: typeof AdminMarketingAnalyticsRouteImport
      parentRoute: typeof AdminMarketingRoute
    }
    '/admin/customers/new': {
      id: '/admin/customers/new'
      path: '/new'
      fullPath: '/admin/customers/new'
      preLoaderRoute: typeof AdminCustomersNewRouteImport
      parentRoute: typeof AdminCustomersRoute
    }
    '/admin/customers/inactive': {
      id: '/admin/customers/inactive'
      path: '/inactive'
      fullPath: '/admin/customers/inactive'
      preLoaderRoute: typeof AdminCustomersInactiveRouteImport
      parentRoute: typeof AdminCustomersRoute
    }
    '/admin/customers/all-time': {
      id: '/admin/customers/all-time'
      path: '/all-time'
      fullPath: '/admin/customers/all-time'
      preLoaderRoute: typeof AdminCustomersAllTimeRouteImport
      parentRoute: typeof AdminCustomersRoute
    }
    '/admin/customers/active': {
      id: '/admin/customers/active'
      path: '/active'
      fullPath: '/admin/customers/active'
      preLoaderRoute: typeof AdminCustomersActiveRouteImport
      parentRoute: typeof AdminCustomersRoute
    }
    '/admin/customers/$userId': {
      id: '/admin/customers/$userId'
      path: '/$userId'
      fullPath: '/admin/customers/$userId'
      preLoaderRoute: typeof AdminCustomersUserIdRouteImport
      parentRoute: typeof AdminCustomersRoute
    }
    '/admin/blog/tags': {
      id: '/admin/blog/tags'
      path: '/tags'
      fullPath: '/admin/blog/tags'
      preLoaderRoute: typeof AdminBlogTagsRouteImport
      parentRoute: typeof AdminBlogRoute
    }
    '/admin/blog/settings': {
      id: '/admin/blog/settings'
      path: '/settings'
      fullPath: '/admin/blog/settings'
      preLoaderRoute: typeof AdminBlogSettingsRouteImport
      parentRoute: typeof AdminBlogRoute
    }
    '/admin/blog/new': {
      id: '/admin/blog/new'
      path: '/new'
      fullPath: '/admin/blog/new'
      preLoaderRoute: typeof AdminBlogNewRouteImport
      parentRoute: typeof AdminBlogRoute
    }
    '/admin/blog/ctas': {
      id: '/admin/blog/ctas'
      path: '/ctas'
      fullPath: '/admin/blog/ctas'
      preLoaderRoute: typeof AdminBlogCtasRouteImport
      parentRoute: typeof AdminBlogRoute
    }
    '/admin/blog/comments': {
      id: '/admin/blog/comments'
      path: '/comments'
      fullPath: '/admin/blog/comments'
      preLoaderRoute: typeof AdminBlogCommentsRouteImport
      parentRoute: typeof AdminBlogRoute
    }
    '/admin/blog/categories': {
      id: '/admin/blog/categories'
      path: '/categories'
      fullPath: '/admin/blog/categories'
      preLoaderRoute: typeof AdminBlogCategoriesRouteImport
      parentRoute: typeof AdminBlogRoute
    }
    '/admin/blog/ai-generator': {
      id: '/admin/blog/ai-generator'
      path: '/ai-generator'
      fullPath: '/admin/blog/ai-generator'
      preLoaderRoute: typeof AdminBlogAiGeneratorRouteImport
      parentRoute: typeof AdminBlogRoute
    }
    '/_authenticated/receipt/$reference': {
      id: '/_authenticated/receipt/$reference'
      path: '/receipt/$reference'
      fullPath: '/receipt/$reference'
      preLoaderRoute: typeof AuthenticatedReceiptReferenceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/order/$slug': {
      id: '/_authenticated/order/$slug'
      path: '/order/$slug'
      fullPath: '/order/$slug'
      preLoaderRoute: typeof AuthenticatedOrderSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/webhooks/paystack': {
      id: '/api/public/webhooks/paystack'
      path: '/api/public/webhooks/paystack'
      fullPath: '/api/public/webhooks/paystack'
      preLoaderRoute: typeof ApiPublicWebhooksPaystackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/monnify': {
      id: '/api/public/webhooks/monnify'
      path: '/api/public/webhooks/monnify'
      fullPath: '/api/public/webhooks/monnify'
      preLoaderRoute: typeof ApiPublicWebhooksMonnifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/flutterwave': {
      id: '/api/public/webhooks/flutterwave'
      path: '/api/public/webhooks/flutterwave'
      fullPath: '/api/public/webhooks/flutterwave'
      preLoaderRoute: typeof ApiPublicWebhooksFlutterwaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/email-dispatcher': {
      id: '/api/public/hooks/email-dispatcher'
      path: '/api/public/hooks/email-dispatcher'
      fullPath: '/api/public/hooks/email-dispatcher'
      preLoaderRoute: typeof ApiPublicHooksEmailDispatcherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/auto-fulfil-private': {
      id: '/api/public/hooks/auto-fulfil-private'
      path: '/api/public/hooks/auto-fulfil-private'
      fullPath: '/api/public/hooks/auto-fulfil-private'
      preLoaderRoute: typeof ApiPublicHooksAutoFulfilPrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog/$id/edit': {
      id: '/admin/blog/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/blog/$id/edit'
      preLoaderRoute: typeof AdminBlogIdEditRouteImport
      parentRoute: typeof AdminBlogRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedChangePasswordRoute: typeof AuthenticatedChangePasswordRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSubscriptionRoute: typeof AuthenticatedSubscriptionRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
  AuthenticatedOrderSlugRoute: typeof AuthenticatedOrderSlugRoute
  AuthenticatedReceiptReferenceRoute: typeof AuthenticatedReceiptReferenceRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedChangePasswordRoute: AuthenticatedChangePasswordRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSubscriptionRoute: AuthenticatedSubscriptionRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
  AuthenticatedOrderSlugRoute: AuthenticatedOrderSlugRoute,
  AuthenticatedReceiptReferenceRoute: AuthenticatedReceiptReferenceRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogSearchRoute: typeof BlogSearchRoute
  BlogIndexRoute: typeof BlogIndexRoute
  BlogAuthorIdRoute: typeof BlogAuthorIdRoute
  BlogCategorySlugRoute: typeof BlogCategorySlugRoute
  BlogTagSlugRoute: typeof BlogTagSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogSearchRoute: BlogSearchRoute,
  BlogIndexRoute: BlogIndexRoute,
  BlogAuthorIdRoute: BlogAuthorIdRoute,
  BlogCategorySlugRoute: BlogCategorySlugRoute,
  BlogTagSlugRoute: BlogTagSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ToolsRouteChildren {
  ToolsSlugRoute: typeof ToolsSlugRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

const ToolsRouteChildren: ToolsRouteChildren = {
  ToolsSlugRoute: ToolsSlugRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}

const ToolsRouteWithChildren = ToolsRoute._addFileChildren(ToolsRouteChildren)

interface AdminBlogRouteChildren {
  AdminBlogAiGeneratorRoute: typeof AdminBlogAiGeneratorRoute
  AdminBlogCategoriesRoute: typeof AdminBlogCategoriesRoute
  AdminBlogCommentsRoute: typeof AdminBlogCommentsRoute
  AdminBlogCtasRoute: typeof AdminBlogCtasRoute
  AdminBlogNewRoute: typeof AdminBlogNewRoute
  AdminBlogSettingsRoute: typeof AdminBlogSettingsRoute
  AdminBlogTagsRoute: typeof AdminBlogTagsRoute
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
  AdminBlogIdEditRoute: typeof AdminBlogIdEditRoute
}

const AdminBlogRouteChildren: AdminBlogRouteChildren = {
  AdminBlogAiGeneratorRoute: AdminBlogAiGeneratorRoute,
  AdminBlogCategoriesRoute: AdminBlogCategoriesRoute,
  AdminBlogCommentsRoute: AdminBlogCommentsRoute,
  AdminBlogCtasRoute: AdminBlogCtasRoute,
  AdminBlogNewRoute: AdminBlogNewRoute,
  AdminBlogSettingsRoute: AdminBlogSettingsRoute,
  AdminBlogTagsRoute: AdminBlogTagsRoute,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
  AdminBlogIdEditRoute: AdminBlogIdEditRoute,
}

const AdminBlogRouteWithChildren = AdminBlogRoute._addFileChildren(
  AdminBlogRouteChildren,
)

interface AdminCustomersRouteChildren {
  AdminCustomersUserIdRoute: typeof AdminCustomersUserIdRoute
  AdminCustomersActiveRoute: typeof AdminCustomersActiveRoute
  AdminCustomersAllTimeRoute: typeof AdminCustomersAllTimeRoute
  AdminCustomersInactiveRoute: typeof AdminCustomersInactiveRoute
  AdminCustomersNewRoute: typeof AdminCustomersNewRoute
  AdminCustomersIndexRoute: typeof AdminCustomersIndexRoute
}

const AdminCustomersRouteChildren: AdminCustomersRouteChildren = {
  AdminCustomersUserIdRoute: AdminCustomersUserIdRoute,
  AdminCustomersActiveRoute: AdminCustomersActiveRoute,
  AdminCustomersAllTimeRoute: AdminCustomersAllTimeRoute,
  AdminCustomersInactiveRoute: AdminCustomersInactiveRoute,
  AdminCustomersNewRoute: AdminCustomersNewRoute,
  AdminCustomersIndexRoute: AdminCustomersIndexRoute,
}

const AdminCustomersRouteWithChildren = AdminCustomersRoute._addFileChildren(
  AdminCustomersRouteChildren,
)

interface AdminMarketingRouteChildren {
  AdminMarketingAnalyticsRoute: typeof AdminMarketingAnalyticsRoute
  AdminMarketingEventsRoute: typeof AdminMarketingEventsRoute
  AdminMarketingGtmRoute: typeof AdminMarketingGtmRoute
  AdminMarketingMetaRoute: typeof AdminMarketingMetaRoute
  AdminMarketingIndexRoute: typeof AdminMarketingIndexRoute
}

const AdminMarketingRouteChildren: AdminMarketingRouteChildren = {
  AdminMarketingAnalyticsRoute: AdminMarketingAnalyticsRoute,
  AdminMarketingEventsRoute: AdminMarketingEventsRoute,
  AdminMarketingGtmRoute: AdminMarketingGtmRoute,
  AdminMarketingMetaRoute: AdminMarketingMetaRoute,
  AdminMarketingIndexRoute: AdminMarketingIndexRoute,
}

const AdminMarketingRouteWithChildren = AdminMarketingRoute._addFileChildren(
  AdminMarketingRouteChildren,
)

interface AdminSettingsRouteChildren {
  AdminSettingsActivityRoute: typeof AdminSettingsActivityRoute
  AdminSettingsAnalyticsRoute: typeof AdminSettingsAnalyticsRoute
  AdminSettingsApiKeysRoute: typeof AdminSettingsApiKeysRoute
  AdminSettingsBackupRoute: typeof AdminSettingsBackupRoute
  AdminSettingsBrowserAuthRoute: typeof AdminSettingsBrowserAuthRoute
  AdminSettingsCommunicationsRoute: typeof AdminSettingsCommunicationsRoute
  AdminSettingsCouponsRoute: typeof AdminSettingsCouponsRoute
  AdminSettingsCurrencyRoute: typeof AdminSettingsCurrencyRoute
  AdminSettingsCustomPaymentsRoute: typeof AdminSettingsCustomPaymentsRoute
  AdminSettingsEmailRoute: typeof AdminSettingsEmailRoute
  AdminSettingsEmergencyRoute: typeof AdminSettingsEmergencyRoute
  AdminSettingsMigrationRoute: typeof AdminSettingsMigrationRoute
  AdminSettingsMigrationGuideRoute: typeof AdminSettingsMigrationGuideRoute
  AdminSettingsMigrationReadinessRoute: typeof AdminSettingsMigrationReadinessRoute
  AdminSettingsPaymentRecoveryRoute: typeof AdminSettingsPaymentRecoveryRoute
  AdminSettingsProductionReadinessRoute: typeof AdminSettingsProductionReadinessRoute
  AdminSettingsPromotionsRoute: typeof AdminSettingsPromotionsRoute
  AdminSettingsStaffRoute: typeof AdminSettingsStaffRoute
  AdminSettingsSystemHealthRoute: typeof AdminSettingsSystemHealthRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
}

const AdminSettingsRouteChildren: AdminSettingsRouteChildren = {
  AdminSettingsActivityRoute: AdminSettingsActivityRoute,
  AdminSettingsAnalyticsRoute: AdminSettingsAnalyticsRoute,
  AdminSettingsApiKeysRoute: AdminSettingsApiKeysRoute,
  AdminSettingsBackupRoute: AdminSettingsBackupRoute,
  AdminSettingsBrowserAuthRoute: AdminSettingsBrowserAuthRoute,
  AdminSettingsCommunicationsRoute: AdminSettingsCommunicationsRoute,
  AdminSettingsCouponsRoute: AdminSettingsCouponsRoute,
  AdminSettingsCurrencyRoute: AdminSettingsCurrencyRoute,
  AdminSettingsCustomPaymentsRoute: AdminSettingsCustomPaymentsRoute,
  AdminSettingsEmailRoute: AdminSettingsEmailRoute,
  AdminSettingsEmergencyRoute: AdminSettingsEmergencyRoute,
  AdminSettingsMigrationRoute: AdminSettingsMigrationRoute,
  AdminSettingsMigrationGuideRoute: AdminSettingsMigrationGuideRoute,
  AdminSettingsMigrationReadinessRoute: AdminSettingsMigrationReadinessRoute,
  AdminSettingsPaymentRecoveryRoute: AdminSettingsPaymentRecoveryRoute,
  AdminSettingsProductionReadinessRoute: AdminSettingsProductionReadinessRoute,
  AdminSettingsPromotionsRoute: AdminSettingsPromotionsRoute,
  AdminSettingsStaffRoute: AdminSettingsStaffRoute,
  AdminSettingsSystemHealthRoute: AdminSettingsSystemHealthRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
}

const AdminSettingsRouteWithChildren = AdminSettingsRoute._addFileChildren(
  AdminSettingsRouteChildren,
)

interface AdminToolsRouteChildren {
  AdminToolsSlugRoute: typeof AdminToolsSlugRoute
  AdminToolsNewRoute: typeof AdminToolsNewRoute
  AdminToolsIndexRoute: typeof AdminToolsIndexRoute
}

const AdminToolsRouteChildren: AdminToolsRouteChildren = {
  AdminToolsSlugRoute: AdminToolsSlugRoute,
  AdminToolsNewRoute: AdminToolsNewRoute,
  AdminToolsIndexRoute: AdminToolsIndexRoute,
}

const AdminToolsRouteWithChildren = AdminToolsRoute._addFileChildren(
  AdminToolsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  ToolsRoute: ToolsRouteWithChildren,
  DotwellKnownAppleDeveloperMerchantidDomainAssociationRoute:
    DotwellKnownAppleDeveloperMerchantidDomainAssociationRoute,
  AdminAccessHealthRoute: AdminAccessHealthRoute,
  AdminAdminsRoute: AdminAdminsRoute,
  AdminAppearanceRoute: AdminAppearanceRoute,
  AdminAwaitingAssignmentsRoute: AdminAwaitingAssignmentsRoute,
  AdminBlogRoute: AdminBlogRouteWithChildren,
  AdminCredentialsRoute: AdminCredentialsRoute,
  AdminCustomersRoute: AdminCustomersRouteWithChildren,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminMarketingRoute: AdminMarketingRouteWithChildren,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSettingsRoute: AdminSettingsRouteWithChildren,
  AdminToolsRoute: AdminToolsRouteWithChildren,
  AdminTransactionsRoute: AdminTransactionsRoute,
  PayTokenRoute: PayTokenRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiDiagOneClickE2e8c54e3bf2a704b8cb468db34d36a1c7aRoute:
    ApiDiagOneClickE2e8c54e3bf2a704b8cb468db34d36a1c7aRoute,
  ApiDiagPhraslyConcurrencyE2eC7a1f3a87d9e4e54b8bd2a7317e63521Route:
    ApiDiagPhraslyConcurrencyE2eC7a1f3a87d9e4e54b8bd2a7317e63521Route,
  ApiDiagPhraslyOtpE2e5d90d80acb9f4e5d9fd0d0a4e02b9e71Route:
    ApiDiagPhraslyOtpE2e5d90d80acb9f4e5d9fd0d0a4e02b9e71Route,
  ApiDiagPhraslyOtpTest4d4dc2a5e7f64203a34e33f071a94554Route:
    ApiDiagPhraslyOtpTest4d4dc2a5e7f64203a34e33f071a94554Route,
  ApiDiagWriterAuthResetE2e820b5d66d7e8ca6d74a3fbc5fb108060Route:
    ApiDiagWriterAuthResetE2e820b5d66d7e8ca6d74a3fbc5fb108060Route,
  ApiPublicBrandLogoRoute: ApiPublicBrandLogoRoute,
  ApiSsoSneakwriteConsumeRoute: ApiSsoSneakwriteConsumeRoute,
  ApiPublicHooksAutoFulfilPrivateRoute: ApiPublicHooksAutoFulfilPrivateRoute,
  ApiPublicHooksEmailDispatcherRoute: ApiPublicHooksEmailDispatcherRoute,
  ApiPublicWebhooksFlutterwaveRoute: ApiPublicWebhooksFlutterwaveRoute,
  ApiPublicWebhooksMonnifyRoute: ApiPublicWebhooksMonnifyRoute,
  ApiPublicWebhooksPaystackRoute: ApiPublicWebhooksPaystackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
