/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ToolsSlugRouteImport } from './routes/tools.$slug'
import { Route as BlogSearchRouteImport } from './routes/blog.search'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminToolsRouteImport } from './routes/admin.tools'
import { Route as AdminPricingRouteImport } from './routes/admin.pricing'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCredentialsRouteImport } from './routes/admin.credentials'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminAppearanceRouteImport } from './routes/admin.appearance'
import { Route as AdminAdminsRouteImport } from './routes/admin.admins'
import { Route as AuthenticatedSubscriptionRouteImport } from './routes/_authenticated.subscription'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated.orders'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated.billing'
import { Route as AdminToolsIndexRouteImport } from './routes/admin.tools.index'
import { Route as AdminBlogIndexRouteImport } from './routes/admin.blog.index'
import { Route as BlogTagSlugRouteImport } from './routes/blog.tag.$slug'
import { Route as BlogCategorySlugRouteImport } from './routes/blog.category.$slug'
import { Route as BlogAuthorIdRouteImport } from './routes/blog.author.$id'
import { Route as AdminToolsSlugRouteImport } from './routes/admin.tools.$slug'
import { Route as AdminBlogTagsRouteImport } from './routes/admin.blog.tags'
import { Route as AdminBlogSettingsRouteImport } from './routes/admin.blog.settings'
import { Route as AdminBlogNewRouteImport } from './routes/admin.blog.new'
import { Route as AdminBlogCtasRouteImport } from './routes/admin.blog.ctas'
import { Route as AdminBlogCommentsRouteImport } from './routes/admin.blog.comments'
import { Route as AdminBlogCategoriesRouteImport } from './routes/admin.blog.categories'
import { Route as AdminBlogAiGeneratorRouteImport } from './routes/admin.blog.ai-generator'
import { Route as AuthenticatedOrderSlugRouteImport } from './routes/_authenticated.order.$slug'
import { Route as ApiPublicWebhooksPaystackRouteImport } from './routes/api.public.webhooks.paystack'
import { Route as ApiPublicHooksAutoFulfilPrivateRouteImport } from './routes/api.public.hooks.auto-fulfil-private'
import { Route as AdminBlogIdEditRouteImport } from './routes/admin.blog.$id.edit'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ToolsRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSlugRoute = ToolsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ToolsRoute,
} as any)
const BlogSearchRoute = BlogSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AdminToolsRoute = AdminToolsRouteImport.update({
  id: '/admin/tools',
  path: '/admin/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/admin/pricing',
  path: '/admin/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCredentialsRoute = AdminCredentialsRouteImport.update({
  id: '/admin/credentials',
  path: '/admin/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/admin/blog',
  path: '/admin/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAppearanceRoute = AdminAppearanceRouteImport.update({
  id: '/admin/appearance',
  path: '/admin/appearance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminsRoute = AdminAdminsRouteImport.update({
  id: '/admin/admins',
  path: '/admin/admins',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSubscriptionRoute =
  AuthenticatedSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AdminToolsIndexRoute = AdminToolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminToolsRoute,
} as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminBlogRoute,
} as any)
const BlogTagSlugRoute = BlogTagSlugRouteImport.update({
  id: '/tag/$slug',
  path: '/tag/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const BlogCategorySlugRoute = BlogCategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const BlogAuthorIdRoute = BlogAuthorIdRouteImport.update({
  id: '/author/$id',
  path: '/author/$id',
  getParentRoute: () => BlogRoute,
} as any)
const AdminToolsSlugRoute = AdminToolsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AdminToolsRoute,
} as any)
const AdminBlogTagsRoute = AdminBlogTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AdminBlogRoute,
} as any)
const AdminBlogSettingsRoute = AdminBlogSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminBlogRoute,
} as any)
const AdminBlogNewRoute = AdminBlogNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminBlogRoute,
} as any)
const AdminBlogCtasRoute = AdminBlogCtasRouteImport.update({
  id: '/ctas',
  path: '/ctas',
  getParentRoute: () => AdminBlogRoute,
} as any)
const AdminBlogCommentsRoute = AdminBlogCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => AdminBlogRoute,
} as any)
const AdminBlogCategoriesRoute = AdminBlogCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminBlogRoute,
} as any)
const AdminBlogAiGeneratorRoute = AdminBlogAiGeneratorRouteImport.update({
  id: '/ai-generator',
  path: '/ai-generator',
  getParentRoute: () => AdminBlogRoute,
} as any)
const AuthenticatedOrderSlugRoute = AuthenticatedOrderSlugRouteImport.update({
  id: '/order/$slug',
  path: '/order/$slug',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicWebhooksPaystackRoute =
  ApiPublicWebhooksPaystackRouteImport.update({
    id: '/api/public/webhooks/paystack',
    path: '/api/public/webhooks/paystack',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAutoFulfilPrivateRoute =
  ApiPublicHooksAutoFulfilPrivateRouteImport.update({
    id: '/api/public/hooks/auto-fulfil-private',
    path: '/api/public/hooks/auto-fulfil-private',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminBlogIdEditRoute = AdminBlogIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminBlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/appearance': typeof AdminAppearanceRoute
  '/admin/blog': typeof AdminBlogRouteWithChildren
  '/admin/credentials': typeof AdminCredentialsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/tools': typeof AdminToolsRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/search': typeof BlogSearchRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/order/$slug': typeof AuthenticatedOrderSlugRoute
  '/admin/blog/ai-generator': typeof AdminBlogAiGeneratorRoute
  '/admin/blog/categories': typeof AdminBlogCategoriesRoute
  '/admin/blog/comments': typeof AdminBlogCommentsRoute
  '/admin/blog/ctas': typeof AdminBlogCtasRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/blog/settings': typeof AdminBlogSettingsRoute
  '/admin/blog/tags': typeof AdminBlogTagsRoute
  '/admin/tools/$slug': typeof AdminToolsSlugRoute
  '/blog/author/$id': typeof BlogAuthorIdRoute
  '/blog/category/$slug': typeof BlogCategorySlugRoute
  '/blog/tag/$slug': typeof BlogTagSlugRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/tools/': typeof AdminToolsIndexRoute
  '/admin/blog/$id/edit': typeof AdminBlogIdEditRoute
  '/api/public/hooks/auto-fulfil-private': typeof ApiPublicHooksAutoFulfilPrivateRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/appearance': typeof AdminAppearanceRoute
  '/admin/credentials': typeof AdminCredentialsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/search': typeof BlogSearchRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/order/$slug': typeof AuthenticatedOrderSlugRoute
  '/admin/blog/ai-generator': typeof AdminBlogAiGeneratorRoute
  '/admin/blog/categories': typeof AdminBlogCategoriesRoute
  '/admin/blog/comments': typeof AdminBlogCommentsRoute
  '/admin/blog/ctas': typeof AdminBlogCtasRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/blog/settings': typeof AdminBlogSettingsRoute
  '/admin/blog/tags': typeof AdminBlogTagsRoute
  '/admin/tools/$slug': typeof AdminToolsSlugRoute
  '/blog/author/$id': typeof BlogAuthorIdRoute
  '/blog/category/$slug': typeof BlogCategorySlugRoute
  '/blog/tag/$slug': typeof BlogTagSlugRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/admin/tools': typeof AdminToolsIndexRoute
  '/admin/blog/$id/edit': typeof AdminBlogIdEditRoute
  '/api/public/hooks/auto-fulfil-private': typeof ApiPublicHooksAutoFulfilPrivateRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/subscription': typeof AuthenticatedSubscriptionRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/appearance': typeof AdminAppearanceRoute
  '/admin/blog': typeof AdminBlogRouteWithChildren
  '/admin/credentials': typeof AdminCredentialsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/tools': typeof AdminToolsRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/search': typeof BlogSearchRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/_authenticated/order/$slug': typeof AuthenticatedOrderSlugRoute
  '/admin/blog/ai-generator': typeof AdminBlogAiGeneratorRoute
  '/admin/blog/categories': typeof AdminBlogCategoriesRoute
  '/admin/blog/comments': typeof AdminBlogCommentsRoute
  '/admin/blog/ctas': typeof AdminBlogCtasRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/blog/settings': typeof AdminBlogSettingsRoute
  '/admin/blog/tags': typeof AdminBlogTagsRoute
  '/admin/tools/$slug': typeof AdminToolsSlugRoute
  '/blog/author/$id': typeof BlogAuthorIdRoute
  '/blog/category/$slug': typeof BlogCategorySlugRoute
  '/blog/tag/$slug': typeof BlogTagSlugRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/tools/': typeof AdminToolsIndexRoute
  '/admin/blog/$id/edit': typeof AdminBlogIdEditRoute
  '/api/public/hooks/auto-fulfil-private': typeof ApiPublicHooksAutoFulfilPrivateRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/cookies'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/tools'
    | '/billing'
    | '/dashboard'
    | '/orders'
    | '/profile'
    | '/subscription'
    | '/admin/admins'
    | '/admin/appearance'
    | '/admin/blog'
    | '/admin/credentials'
    | '/admin/dashboard'
    | '/admin/orders'
    | '/admin/pricing'
    | '/admin/tools'
    | '/blog/$slug'
    | '/blog/search'
    | '/tools/$slug'
    | '/admin/'
    | '/blog/'
    | '/tools/'
    | '/order/$slug'
    | '/admin/blog/ai-generator'
    | '/admin/blog/categories'
    | '/admin/blog/comments'
    | '/admin/blog/ctas'
    | '/admin/blog/new'
    | '/admin/blog/settings'
    | '/admin/blog/tags'
    | '/admin/tools/$slug'
    | '/blog/author/$id'
    | '/blog/category/$slug'
    | '/blog/tag/$slug'
    | '/admin/blog/'
    | '/admin/tools/'
    | '/admin/blog/$id/edit'
    | '/api/public/hooks/auto-fulfil-private'
    | '/api/public/webhooks/paystack'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/cookies'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/billing'
    | '/dashboard'
    | '/orders'
    | '/profile'
    | '/subscription'
    | '/admin/admins'
    | '/admin/appearance'
    | '/admin/credentials'
    | '/admin/dashboard'
    | '/admin/orders'
    | '/admin/pricing'
    | '/blog/$slug'
    | '/blog/search'
    | '/tools/$slug'
    | '/admin'
    | '/blog'
    | '/tools'
    | '/order/$slug'
    | '/admin/blog/ai-generator'
    | '/admin/blog/categories'
    | '/admin/blog/comments'
    | '/admin/blog/ctas'
    | '/admin/blog/new'
    | '/admin/blog/settings'
    | '/admin/blog/tags'
    | '/admin/tools/$slug'
    | '/blog/author/$id'
    | '/blog/category/$slug'
    | '/blog/tag/$slug'
    | '/admin/blog'
    | '/admin/tools'
    | '/admin/blog/$id/edit'
    | '/api/public/hooks/auto-fulfil-private'
    | '/api/public/webhooks/paystack'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/blog'
    | '/contact'
    | '/cookies'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/tools'
    | '/_authenticated/billing'
    | '/_authenticated/dashboard'
    | '/_authenticated/orders'
    | '/_authenticated/profile'
    | '/_authenticated/subscription'
    | '/admin/admins'
    | '/admin/appearance'
    | '/admin/blog'
    | '/admin/credentials'
    | '/admin/dashboard'
    | '/admin/orders'
    | '/admin/pricing'
    | '/admin/tools'
    | '/blog/$slug'
    | '/blog/search'
    | '/tools/$slug'
    | '/admin/'
    | '/blog/'
    | '/tools/'
    | '/_authenticated/order/$slug'
    | '/admin/blog/ai-generator'
    | '/admin/blog/categories'
    | '/admin/blog/comments'
    | '/admin/blog/ctas'
    | '/admin/blog/new'
    | '/admin/blog/settings'
    | '/admin/blog/tags'
    | '/admin/tools/$slug'
    | '/blog/author/$id'
    | '/blog/category/$slug'
    | '/blog/tag/$slug'
    | '/admin/blog/'
    | '/admin/tools/'
    | '/admin/blog/$id/edit'
    | '/api/public/hooks/auto-fulfil-private'
    | '/api/public/webhooks/paystack'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  ToolsRoute: typeof ToolsRouteWithChildren
  AdminAdminsRoute: typeof AdminAdminsRoute
  AdminAppearanceRoute: typeof AdminAppearanceRoute
  AdminBlogRoute: typeof AdminBlogRouteWithChildren
  AdminCredentialsRoute: typeof AdminCredentialsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminToolsRoute: typeof AdminToolsRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  ApiPublicHooksAutoFulfilPrivateRoute: typeof ApiPublicHooksAutoFulfilPrivateRoute
  ApiPublicWebhooksPaystackRoute: typeof ApiPublicWebhooksPaystackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$slug': {
      id: '/tools/$slug'
      path: '/$slug'
      fullPath: '/tools/$slug'
      preLoaderRoute: typeof ToolsSlugRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/blog/search': {
      id: '/blog/search'
      path: '/search'
      fullPath: '/blog/search'
      preLoaderRoute: typeof BlogSearchRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/tools': {
      id: '/admin/tools'
      path: '/admin/tools'
      fullPath: '/admin/tools'
      preLoaderRoute: typeof AdminToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/admin/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/credentials': {
      id: '/admin/credentials'
      path: '/admin/credentials'
      fullPath: '/admin/credentials'
      preLoaderRoute: typeof AdminCredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/admin/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/appearance': {
      id: '/admin/appearance'
      path: '/admin/appearance'
      fullPath: '/admin/appearance'
      preLoaderRoute: typeof AdminAppearanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/admins': {
      id: '/admin/admins'
      path: '/admin/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/subscription': {
      id: '/_authenticated/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof AuthenticatedSubscriptionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/admin/tools/': {
      id: '/admin/tools/'
      path: '/'
      fullPath: '/admin/tools/'
      preLoaderRoute: typeof AdminToolsIndexRouteImport
      parentRoute: typeof AdminToolsRoute
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof AdminBlogRoute
    }
    '/blog/tag/$slug': {
      id: '/blog/tag/$slug'
      path: '/tag/$slug'
      fullPath: '/blog/tag/$slug'
      preLoaderRoute: typeof BlogTagSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/category/$slug': {
      id: '/blog/category/$slug'
      path: '/category/$slug'
      fullPath: '/blog/category/$slug'
      preLoaderRoute: typeof BlogCategorySlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/author/$id': {
      id: '/blog/author/$id'
      path: '/author/$id'
      fullPath: '/blog/author/$id'
      preLoaderRoute: typeof BlogAuthorIdRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/tools/$slug': {
      id: '/admin/tools/$slug'
      path: '/$slug'
      fullPath: '/admin/tools/$slug'
      preLoaderRoute: typeof AdminToolsSlugRouteImport
      parentRoute: typeof AdminToolsRoute
    }
    '/admin/blog/tags': {
      id: '/admin/blog/tags'
      path: '/tags'
      fullPath: '/admin/blog/tags'
      preLoaderRoute: typeof AdminBlogTagsRouteImport
      parentRoute: typeof AdminBlogRoute
    }
    '/admin/blog/settings': {
      id: '/admin/blog/settings'
      path: '/settings'
      fullPath: '/admin/blog/settings'
      preLoaderRoute: typeof AdminBlogSettingsRouteImport
      parentRoute: typeof AdminBlogRoute
    }
    '/admin/blog/new': {
      id: '/admin/blog/new'
      path: '/new'
      fullPath: '/admin/blog/new'
      preLoaderRoute: typeof AdminBlogNewRouteImport
      parentRoute: typeof AdminBlogRoute
    }
    '/admin/blog/ctas': {
      id: '/admin/blog/ctas'
      path: '/ctas'
      fullPath: '/admin/blog/ctas'
      preLoaderRoute: typeof AdminBlogCtasRouteImport
      parentRoute: typeof AdminBlogRoute
    }
    '/admin/blog/comments': {
      id: '/admin/blog/comments'
      path: '/comments'
      fullPath: '/admin/blog/comments'
      preLoaderRoute: typeof AdminBlogCommentsRouteImport
      parentRoute: typeof AdminBlogRoute
    }
    '/admin/blog/categories': {
      id: '/admin/blog/categories'
      path: '/categories'
      fullPath: '/admin/blog/categories'
      preLoaderRoute: typeof AdminBlogCategoriesRouteImport
      parentRoute: typeof AdminBlogRoute
    }
    '/admin/blog/ai-generator': {
      id: '/admin/blog/ai-generator'
      path: '/ai-generator'
      fullPath: '/admin/blog/ai-generator'
      preLoaderRoute: typeof AdminBlogAiGeneratorRouteImport
      parentRoute: typeof AdminBlogRoute
    }
    '/_authenticated/order/$slug': {
      id: '/_authenticated/order/$slug'
      path: '/order/$slug'
      fullPath: '/order/$slug'
      preLoaderRoute: typeof AuthenticatedOrderSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/webhooks/paystack': {
      id: '/api/public/webhooks/paystack'
      path: '/api/public/webhooks/paystack'
      fullPath: '/api/public/webhooks/paystack'
      preLoaderRoute: typeof ApiPublicWebhooksPaystackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/auto-fulfil-private': {
      id: '/api/public/hooks/auto-fulfil-private'
      path: '/api/public/hooks/auto-fulfil-private'
      fullPath: '/api/public/hooks/auto-fulfil-private'
      preLoaderRoute: typeof ApiPublicHooksAutoFulfilPrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog/$id/edit': {
      id: '/admin/blog/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/blog/$id/edit'
      preLoaderRoute: typeof AdminBlogIdEditRouteImport
      parentRoute: typeof AdminBlogRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSubscriptionRoute: typeof AuthenticatedSubscriptionRoute
  AuthenticatedOrderSlugRoute: typeof AuthenticatedOrderSlugRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSubscriptionRoute: AuthenticatedSubscriptionRoute,
  AuthenticatedOrderSlugRoute: AuthenticatedOrderSlugRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogSearchRoute: typeof BlogSearchRoute
  BlogIndexRoute: typeof BlogIndexRoute
  BlogAuthorIdRoute: typeof BlogAuthorIdRoute
  BlogCategorySlugRoute: typeof BlogCategorySlugRoute
  BlogTagSlugRoute: typeof BlogTagSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogSearchRoute: BlogSearchRoute,
  BlogIndexRoute: BlogIndexRoute,
  BlogAuthorIdRoute: BlogAuthorIdRoute,
  BlogCategorySlugRoute: BlogCategorySlugRoute,
  BlogTagSlugRoute: BlogTagSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ToolsRouteChildren {
  ToolsSlugRoute: typeof ToolsSlugRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

const ToolsRouteChildren: ToolsRouteChildren = {
  ToolsSlugRoute: ToolsSlugRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}

const ToolsRouteWithChildren = ToolsRoute._addFileChildren(ToolsRouteChildren)

interface AdminBlogRouteChildren {
  AdminBlogAiGeneratorRoute: typeof AdminBlogAiGeneratorRoute
  AdminBlogCategoriesRoute: typeof AdminBlogCategoriesRoute
  AdminBlogCommentsRoute: typeof AdminBlogCommentsRoute
  AdminBlogCtasRoute: typeof AdminBlogCtasRoute
  AdminBlogNewRoute: typeof AdminBlogNewRoute
  AdminBlogSettingsRoute: typeof AdminBlogSettingsRoute
  AdminBlogTagsRoute: typeof AdminBlogTagsRoute
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
  AdminBlogIdEditRoute: typeof AdminBlogIdEditRoute
}

const AdminBlogRouteChildren: AdminBlogRouteChildren = {
  AdminBlogAiGeneratorRoute: AdminBlogAiGeneratorRoute,
  AdminBlogCategoriesRoute: AdminBlogCategoriesRoute,
  AdminBlogCommentsRoute: AdminBlogCommentsRoute,
  AdminBlogCtasRoute: AdminBlogCtasRoute,
  AdminBlogNewRoute: AdminBlogNewRoute,
  AdminBlogSettingsRoute: AdminBlogSettingsRoute,
  AdminBlogTagsRoute: AdminBlogTagsRoute,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
  AdminBlogIdEditRoute: AdminBlogIdEditRoute,
}

const AdminBlogRouteWithChildren = AdminBlogRoute._addFileChildren(
  AdminBlogRouteChildren,
)

interface AdminToolsRouteChildren {
  AdminToolsSlugRoute: typeof AdminToolsSlugRoute
  AdminToolsIndexRoute: typeof AdminToolsIndexRoute
}

const AdminToolsRouteChildren: AdminToolsRouteChildren = {
  AdminToolsSlugRoute: AdminToolsSlugRoute,
  AdminToolsIndexRoute: AdminToolsIndexRoute,
}

const AdminToolsRouteWithChildren = AdminToolsRoute._addFileChildren(
  AdminToolsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  ToolsRoute: ToolsRouteWithChildren,
  AdminAdminsRoute: AdminAdminsRoute,
  AdminAppearanceRoute: AdminAppearanceRoute,
  AdminBlogRoute: AdminBlogRouteWithChildren,
  AdminCredentialsRoute: AdminCredentialsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminToolsRoute: AdminToolsRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  ApiPublicHooksAutoFulfilPrivateRoute: ApiPublicHooksAutoFulfilPrivateRoute,
  ApiPublicWebhooksPaystackRoute: ApiPublicWebhooksPaystackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
